# Generated by Django 6.0.4 on 2026-04-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_type', models.CharField(choices=[('class', 'สอนปกติ/ชดเชย/เสริม'), ('training', 'จัดอบรม/จัดติว')], max_length=20)),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('curriculum', models.CharField(blank=True, choices=[('regular', 'ปริญญาตรีภาคปกติ'), ('master', 'ปริญญาโท'), ('tep_tepe', 'TEP-TEPE'), ('tu_pine', 'TU-PINE')], max_length=20, null=True)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.room')),
            ],
            options={
                'verbose_name': 'การจองห้อง',
                'verbose_name_plural': 'การจองห้อง',
                'ordering': ['-created_at'],
            },
        ),
    ]
