# Generated by Django 6.0.4 on 2026-04-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('regular', 'ปริญญาตรีภาคปกติ'), ('master', 'ปริญญาโท'), ('tep_tepe', 'TEP-TEPE'), ('tu_pine', 'TU-PINE')], max_length=20, null=True, verbose_name='หลักสูตร'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='days_of_week',
            field=models.CharField(max_length=50, verbose_name='วันในสัปดาห์'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='ถึงวันที่'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(verbose_name='ถึงเวลา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose_type',
            field=models.CharField(choices=[('class', 'สอนปกติ/ชดเชย/เสริม'), ('training', 'จัดอบรม/จัดติว')], max_length=20, verbose_name='วัตถุประสงค์'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.room', verbose_name='ห้อง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='ตั้งแต่วันที่'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='ตั้งแต่เวลา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อวิชา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อเรื่อง'),
        ),
    ]
