# Generated by Django 6.0.4 on 2026-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userprofile_tu_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(default='1/2569', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allow_break_booking', models.BooleanField(default=False)),
                ('max_advance_days', models.IntegerField(default=30)),
                ('max_hours', models.IntegerField(default=4)),
                ('auto_approve_lecturer', models.BooleanField(default=True)),
                ('allow_weekend', models.BooleanField(default=True)),
                ('admin_email', models.EmailField(default='admin.tse@thammasat.ac.th', max_length=254)),
                ('enable_email_notification', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'การตั้งค่าระบบ',
                'verbose_name_plural': 'การตั้งค่าระบบ',
            },
        ),
    ]
