# Generated by Django 6.0.4 on 2026-04-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
