# Generated by Django 6.0.4 on 2026-05-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_booking_curriculum_alter_booking_days_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booker',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='booking',
        ),
        migrations.DeleteModel(
            name='BlackoutPeriod',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
