# Generated by Django 6.0.4 on 2026-05-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='auto_approve_lecturer',
        ),
    ]
