version: '3.8'

services:
  web:
    build: .
    container_name: vidva_booking_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # เชื่อมโค้ดในเครื่องเข้ากับใน Docker (แก้โค้ดปุ๊บ อัปเดตปั๊บ)
    restart: always