# Generated by Django 6.0.4 on 2026-05-21 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('meeting', 'ห้องประชุม'), ('classroom', 'ห้องเรียน')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ห้อง',
                'verbose_name_plural': 'ห้อง',
                'ordering': ['room_code'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_type', models.CharField(choices=[('class', 'สอนปกติ/ชดเชย/เสริม'), ('training', 'จัดอบรม/จัดติว')], max_length=20, verbose_name='วัตถุประสงค์')),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อวิชา')),
                ('curriculum', models.CharField(blank=True, choices=[('regular', 'ปริญญาตรีภาคปกติ'), ('master', 'ปริญญาโท'), ('tep_tepe', 'TEP-TEPE'), ('tu_pine', 'TU-PINE')], max_length=20, null=True, verbose_name='หลักสูตร')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อเรื่อง')),
                ('start_date', models.DateField(verbose_name='ตั้งแต่วันที่')),
                ('end_date', models.DateField(verbose_name='ถึงวันที่')),
                ('start_time', models.TimeField(verbose_name='ตั้งแต่เวลา')),
                ('end_time', models.TimeField(verbose_name='ถึงเวลา')),
                ('days_of_week', models.CharField(max_length=50, verbose_name='วันในสัปดาห์')),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Booking.room', verbose_name='ห้อง')),
            ],
            options={
                'verbose_name': 'การจองห้อง',
                'verbose_name_plural': 'การจองห้อง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_booking', 'มีการจองใหม่ (แจ้ง Admin)'), ('status_change', 'สถานะการจองเปลี่ยน (แจ้งผู้จอง)'), ('reminder', 'แจ้งเตือนล่วงหน้า 1 วัน')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Booking.booking')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อช่วงปิด')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blackout_periods', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, related_name='blackout_periods', to='Booking.room', verbose_name='ห้องที่ปิด (ว่าง = ทุกห้อง)')),
            ],
            options={
                'verbose_name': 'ช่วงเวลาปิดใช้งาน',
                'verbose_name_plural': 'ช่วงเวลาปิดใช้งาน',
                'ordering': ['start_date'],
            },
        ),
    ]
