# Generated by Django 6.0.4 on 2026-05-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ภาคการศึกษา (เช่น 1/2569)')),
                ('start_date', models.DateField(verbose_name='วันเริ่มต้นเทอม')),
                ('end_date', models.DateField(verbose_name='วันสิ้นสุดเทอม')),
                ('is_active', models.BooleanField(default=False, verbose_name='เปิดใช้งานเป็นเทอมปัจจุบัน')),
            ],
            options={
                'verbose_name': 'ภาคการศึกษา',
                'verbose_name_plural': 'ภาคการศึกษา',
                'ordering': ['-start_date'],
            },
        ),
    ]
