# Generated by Django 6.0.4 on 2026-05-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_academicsemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='รูปภาพห้อง'),
        ),
    ]
