# Generated by Django 6.0.4 on 2026-05-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_room_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicSemester',
        ),
    ]
